# Generated by Django 3.1.7 on 2021-04-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210310_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrydata',
            name='country',
        ),
        migrations.RemoveField(
            model_name='countrydata',
            name='population',
        ),
        migrations.AddField(
            model_name='countrydata',
            name='Count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countrydata',
            name='Day',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
