# Generated by Django 3.2 on 2021-04-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210409_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Email Subscription',
            },
        ),
    ]
